# Projet 8 : Faire une étude sur l'eau potable (DWFA)

In [2]:
# import librairies needed for project
import numpy as np
import pandas as pd
import psycopg2 #importation librairie postgresql
from psycopg2 import Error
from sqlalchemy import create_engine, text
from sqlalchemy.orm import Session
from sqlalchemy.engine import Row  # Importez Row

## Connection au serveur PostgreSQL

In [4]:
# 1ere approche :

try:
    connection = psycopg2.connect(
        host="localhost",  # Adresse du serveur, corrigée sans 't' supplémentaire
        port=5433,  # Port du serveur
        database="projet_8_oc",  # Nom de la base de données
        user="postgres",  # Nom d'utilisateur
        password="12345"  # Mot de passe
    )

    # Si aucun exception n'est levée, la connexion est considérée comme réussie
    print("Connection to the database successful!")

except Error as e:
    print("Error while connecting to the database:", e)
finally:
    if connection:
        connection.close()
        print("Database connection closed.")

Connection to the database successful!
Database connection closed.

In [5]:
# 2eme approche :

try:
    # Connexion à une base de données PostgreSQL
    connection = psycopg2.connect(
        host="localhost",  # Adresse du serveur
        port=5433,
        database="projet_8_oc",  # Nom de la base de données
        user="postgres",      # Nom d'utilisateur
        password="12345"  # Mot de passe
    )
    
    # Création d'un curseur pour exécuter des opérations sur la base de données
    cursor = connection.cursor()
    
    # Exécution d'une requête
    cursor.execute("SELECT version();")
    
    # Récupération des résultats
    version = cursor.fetchone()
    print("Version de la base de données PostgreSQL :", version)
    
    # Fermeture du curseur
    cursor.close()

except Error as error:
    print("Erreur lors de la connexion à PostgreSQL", error)

finally:
    if connection:
        # Fermeture de la connexion
        connection.close()
        print("Connexion à PostgreSQL fermée")

Version de la base de données PostgreSQL : ('PostgreSQL 16.3, compiled by Visual C++ build 1939, 64-bit',)
Connexion à PostgreSQL fermée

### 1. Création de la table region_country

In [7]:
# Importation du fichier RegionCountry : 
region_country = pd.read_csv('C:/Users/jorda/OneDrive/Documents/Projet_8/dossier_final_septembre/donnees_brut_DAN-P8-donnees/RegionCountry.csv')
region_country.describe()

       REGION (DISPLAY) COUNTRY (DISPLAY)
count               194               194
unique                6               194
top              Europe           Albania
freq                 53                 1

In [8]:
# Vérification des valeurs nulles de region_country :
region_country.isnull().values.any()
print("Contient des valeurs nulles:", region_country.isnull().values.any())
# Résultat : Pas de valeurs nulles

Contient des valeurs nulles: False

In [9]:
# Changement du nom des colonnes :
region_country.rename(columns={'REGION (DISPLAY)': 'region', 'COUNTRY (DISPLAY)':'country'}, inplace=True)

In [10]:
region_country.dtypes

region     object
country    object
dtype: object

In [11]:
# Changement du type des colonnes : (pq 'string : gère mieux les valeurs manquantes et offre une meilleure intégration avec les fonctionnalités de Pandas.)
region_country['country'] = region_country['country'].astype('string')
region_country['region'] = region_country['region'].astype('string')

In [12]:
# Réorganisation des colonnes 
region_country_final = region_country[['region','country']].copy()

In [13]:
# exportation region_country_final en csv
region_country_final.to_csv('region_country_final.csv', index=False)

## 2. Création de la table political_stability

In [15]:
# Importation du fichier  political_stability : 
political_stability = pd.read_csv('C:/Users/jorda/OneDrive/Documents/Projet_8/dossier_final_septembre/donnees_brut_DAN-P8-donnees/PoliticalStability.csv')
political_stability.describe()

              Year  Political_Stability
count  3526.000000          3526.000000
mean   2009.521838            -0.051044
std       5.255833             0.996039
min    2000.000000            -3.310000
25%    2005.000000            -0.710000
50%    2010.000000             0.050000
75%    2014.000000             0.797500
max    2018.000000             1.970000

In [16]:
# Vérification des valeurs nulles de region_country :
political_stability.isnull().values.any()
print("Contient des valeurs nulles:", political_stability.isnull().values.any())
# Résultat : Pas de valeurs nulles

Contient des valeurs nulles: False

In [17]:
# Changement des noms des colonnes :
political_stability.rename(columns={'Country': 'country', 'Year':'year', 'Political_Stability':'political_stability'}, inplace=True)

In [18]:
# Changement du type des colonnes : 
political_stability['country'] = political_stability['country'].astype('string')
political_stability['year'] = political_stability['year'].astype('int')
political_stability['political_stability'] = political_stability['political_stability'].astype('float')

In [19]:
print("Nombre de pays dans la liste de la table politival_stability :",political_stability['country'].nunique())
print("Nombre de doublons dans la table politival_stability :" ,political_stability.duplicated().sum())

Nombre de pays dans la liste de la table politival_stability : 200
Nombre de doublons dans la table politival_stability : 0

#### Création de la fonction de filtrage : find_missing_elements pour vérifier si les pays de la table region_country sont dans la table political stability et celle de la table population (un peu plus bas).

Objectif : filtrer une liste en éliminant les éléments qui sont déjà présents dans une autre liste.

In [21]:
# Fonction permettant d'identifier les éléments de la première liste qui ne figurent pas dans la deuxième, pour ensuite créer une liste 
# de ces éléments absents.
def find_missing_elements(liste1, liste2):
    # Création de sets pour une recherche plus rapide
    set1 = set(liste1)
    set2 = set(liste2)
    # Utilisation de la différence d'ensembles pour trouver les éléments manquants
    missing_elements = list(set1 - set2)
    return missing_elements

In [22]:
# Vérification des pays avec le filtre de la fonction :
print("Pays inclus dans les mesures de stabilité politique mais manquants dans le registre des pays :")
region_country_out = find_missing_elements(political_stability['country'].unique().tolist(), region_country['country'].unique().tolist())
print(region_country_out)

Pays inclus dans les mesures de stabilité politique mais manquants dans le registre des pays :
['Greenland', 'Palestine', 'China, mainland', 'American Samoa', 'China, Macao SAR', 'Puerto Rico', 'China, Taiwan Province of', 'Bermuda', 'China, Hong Kong SAR', 'North Macedonia']

In [23]:
print("Pays inclus dans le registre des pays mais manquants dans les indices de stabilité politique :")
find_missing_elements(region_country['country'].unique().tolist(), political_stability['country'].unique().tolist())

Pays inclus dans le registre des pays mais manquants dans les indices de stabilité politique :

['Republic of North Macedonia', 'San Marino', 'Monaco', 'China']

In [24]:
# Remplacement du nom 'China, mainland' par le nom 'China' venant de region_country :
political_stability.loc[(political_stability['country'] == 'China, mainland'), 'country'] = 'China'

In [25]:
# Suppression des pays n'ayant pas d'indice de stabilité politique :   
ps_less_missing_v = political_stability.loc[(political_stability['country'].isin(region_country_out) == False)].copy()

In [26]:
# Réorganisation des colonnes 
political_stability_final = ps_less_missing_v[['country', 'year','political_stability']].copy()

In [27]:
# exportation political_stability_final en csv
political_stability_final.to_csv('political_stability_final.csv', index=False)

## 3. Création de la  table population

In [29]:
# Importation du fichier  Population : 
population = pd.read_csv('C:/Users/jorda/OneDrive/Documents/Projet_8/dossier_final_septembre/donnees_brut_DAN-P8-donnees/Population.csv')
population.describe()

               Year    Population
count  20914.000000  2.091400e+04
mean    2009.046715  2.253164e+04
std        5.479195  1.000169e+05
min     2000.000000  0.000000e+00
25%     2004.000000  3.483462e+02
50%     2009.000000  3.016337e+03
75%     2014.000000  1.115043e+04
max     2018.000000  1.459378e+06

In [30]:
# Vérification des valeurs nulles de region_country :
population.isnull().values.any()
print("Contient des valeurs nulles:", population.isnull().values.any())
# Résultat : Pas de valeurs nulles

Contient des valeurs nulles: False

In [31]:
# Changement du nom des colonnes :
population.rename(columns={'Country': 'country', 'Year':'year', 'Granularity':'granularity', 'Population':'population'}, inplace=True)
population

           country granularity  year  population
0      Afghanistan       Total  2000   20779.953
1      Afghanistan        Male  2000   10689.508
2      Afghanistan      Female  2000   10090.449
3      Afghanistan       Rural  2000   15657.474
4      Afghanistan       Urban  2000    4436.282
...            ...         ...   ...         ...
20909     Zimbabwe       Total  2018   14438.802
20910     Zimbabwe        Male  2018    6879.119
20911     Zimbabwe      Female  2018    7559.693
20912     Zimbabwe       Rural  2018   11465.748
20913     Zimbabwe       Urban  2018    5447.513

[20914 rows x 4 columns]

In [32]:
# Transfomration de la table en pivot pour avoir une colonne pour chaque modalités de la colonne 'granularity' :
population_pivot = population.pivot(index=['country','year'], columns='granularity', values='population').reset_index()
population_pivot.head()

granularity,country,year,Female,Male,Rural,Total,Urban
0,Afghanistan,2000,10090.449,10689.508,15657.474,20779.953,4436.282
1,Afghanistan,2001,10489.238,11117.754,16318.324,21606.988,4648.139
2,Afghanistan,2002,10958.668,11642.106,17086.910,22600.770,4893.013
3,Afghanistan,2003,11466.237,12214.634,17909.063,23680.871,5155.788
4,Afghanistan,2004,11962.963,12763.726,18692.107,24726.684,5426.872

In [33]:
# Changement du nom des colonnes :
population_pivot.rename(columns={'Female': 'female', 'Male':'male', 'Rural':'rural', 'Total':'total','Urban':'urban'}, inplace=True)
population_pivot

granularity,country,year,female,male,rural,total,urban
0,Afghanistan,2000,10090.449,10689.508,15657.474,20779.953,4436.282
1,Afghanistan,2001,10489.238,11117.754,16318.324,21606.988,4648.139
2,Afghanistan,2002,10958.668,11642.106,17086.910,22600.770,4893.013
3,Afghanistan,2003,11466.237,12214.634,17909.063,23680.871,5155.788
4,Afghanistan,2004,11962.963,12763.726,18692.107,24726.684,5426.872
...,...,...,...,...,...,...,...
4425,Zimbabwe,2014,7126.795,6459.915,10402.274,13586.707,5009.401
4426,Zimbabwe,2015,7245.864,6568.778,10667.966,13814.629,5109.485
4427,Zimbabwe,2016,7356.132,6674.206,10934.468,14030.331,5215.894
4428,Zimbabwe,2017,7459.545,6777.054,11201.138,14236.595,5328.766
4429,Zimbabwe,2018,7559.693,6879.119,11465.748,14438.802,5447.513

In [34]:
# Modification des mesures
population_pivot['female'] = population_pivot['female'] * 1000
population_pivot['male'] = population_pivot['male'] * 1000
population_pivot['rural'] = population_pivot['rural'] * 1000
population_pivot['urban'] = population_pivot['urban'] * 1000
population_pivot['total'] = population_pivot['total'] * 1000

In [35]:
population_pivot

granularity,country,year,female,male,rural,total,urban
0,Afghanistan,2000,10090449.0,10689508.0,15657474.0,20779953.0,4436282.0
1,Afghanistan,2001,10489238.0,11117754.0,16318324.0,21606988.0,4648139.0
2,Afghanistan,2002,10958668.0,11642106.0,17086910.0,22600770.0,4893013.0
3,Afghanistan,2003,11466237.0,12214634.0,17909063.0,23680871.0,5155788.0
4,Afghanistan,2004,11962963.0,12763726.0,18692107.0,24726684.0,5426872.0
...,...,...,...,...,...,...,...
4425,Zimbabwe,2014,7126795.0,6459915.0,10402274.0,13586707.0,5009401.0
4426,Zimbabwe,2015,7245864.0,6568778.0,10667966.0,13814629.0,5109485.0
4427,Zimbabwe,2016,7356132.0,6674206.0,10934468.0,14030331.0,5215894.0
4428,Zimbabwe,2017,7459545.0,6777054.0,11201138.0,14236595.0,5328766.0
4429,Zimbabwe,2018,7559693.0,6879119.0,11465748.0,14438802.0,5447513.0

In [36]:
# Réorganisation des colonnes 
population = population_pivot[['country', 'year', 'total','female','male','rural','urban']].copy()

In [37]:
population

granularity,country,year,total,female,male,rural,urban
0,Afghanistan,2000,20779953.0,10090449.0,10689508.0,15657474.0,4436282.0
1,Afghanistan,2001,21606988.0,10489238.0,11117754.0,16318324.0,4648139.0
2,Afghanistan,2002,22600770.0,10958668.0,11642106.0,17086910.0,4893013.0
3,Afghanistan,2003,23680871.0,11466237.0,12214634.0,17909063.0,5155788.0
4,Afghanistan,2004,24726684.0,11962963.0,12763726.0,18692107.0,5426872.0
...,...,...,...,...,...,...,...
4425,Zimbabwe,2014,13586707.0,7126795.0,6459915.0,10402274.0,5009401.0
4426,Zimbabwe,2015,13814629.0,7245864.0,6568778.0,10667966.0,5109485.0
4427,Zimbabwe,2016,14030331.0,7356132.0,6674206.0,10934468.0,5215894.0
4428,Zimbabwe,2017,14236595.0,7459545.0,6777054.0,11201138.0,5328766.0
4429,Zimbabwe,2018,14438802.0,7559693.0,6879119.0,11465748.0,5447513.0

In [38]:
print("Liste des pays avec des données démographiques non répertoriés dans l'index des pays :")
region_country_out_2 = find_missing_elements(population['country'].unique().tolist(), region_country['country'].unique().tolist())
print(region_country_out_2)

Liste des pays avec des données démographiques non répertoriés dans l'index des pays :
['New Caledonia', 'Palestine', 'Saint Pierre and Miquelon', 'China, Taiwan Province of', 'Liechtenstein', 'Isle of Man', 'Bermuda', 'Falkland Islands (Malvinas)', 'Martinique', 'Saint Helena, Ascension and Tristan da Cunha', 'French Guyana', 'Saint-Martin (French part)', 'Mayotte', 'Netherlands Antilles (former)', 'Turks and Caicos Islands', 'Bonaire, Sint Eustatius and Saba', 'Sint Maarten  (Dutch part)', 'Gibraltar', 'American Samoa', 'Cayman Islands', 'North Macedonia', 'China, Hong Kong SAR', 'Réunion', 'Western Sahara', 'Saint Barthélemy', 'Wallis and Futuna Islands', 'Guadeloupe', 'Greenland', 'British Virgin Islands', 'China, Macao SAR', 'Puerto Rico', 'Holy See', 'Channel Islands', 'Serbia and Montenegro', 'Faroe Islands', 'Guam', 'Anguilla', 'Sudan (former)', 'Tokelau', 'Montserrat', 'Curaçao', 'China, mainland', 'United States Virgin Islands', 'French Polynesia', 'Northern Mariana Islands', 'Aruba']

In [39]:
print("Pays de l'index sans données de population :")
find_missing_elements(region_country['country'].unique().tolist(), population['country'].unique().tolist())

Pays de l'index sans données de population :

['Republic of North Macedonia']

In [40]:
# Identification des lignes contenant des valeurs manquantes :
missing_v_population = population[population.isnull().any(axis=1)]
# Extraction des noms de pays uniques avec des données manquantes :
region_country_out_3 = missing_v_population['country'].unique()
print(region_country_out_3)

['American Samoa' 'Andorra' 'Anguilla' 'Bermuda'
 'Bonaire, Sint Eustatius and Saba' 'British Virgin Islands'
 'Cayman Islands' 'Cook Islands' 'Dominica' 'Falkland Islands (Malvinas)'
 'Faroe Islands' 'Gibraltar' 'Greenland' 'Holy See' 'Isle of Man'
 'Liechtenstein' 'Marshall Islands' 'Monaco' 'Montserrat' 'Nauru' 'Niue'
 'Northern Mariana Islands' 'Palau' 'Saint Barthélemy'
 'Saint Helena, Ascension and Tristan da Cunha' 'Saint Kitts and Nevis'
 'Saint Pierre and Miquelon' 'Saint-Martin (French part)' 'San Marino'
 'Sint Maarten  (Dutch part)' 'Tokelau' 'Turks and Caicos Islands'
 'Tuvalu' 'Wallis and Futuna Islands']

In [41]:
# Suppression des pays ayant des données incomplètes ou étant des territoires dépendants d'autres pays.
population_final = population.loc[(population['country'].isin(region_country_out_2) == False)
                                 & (population['country'].isin(region_country_out_3) == False)].copy()

In [42]:
find_missing_elements(population_final['country'].unique().tolist(), region_country['country'].unique().tolist())
# Cette fonction retourne une liste des pays qui sont présents dans population_final mais qui ne figurent pas dans region_country.

[]

In [43]:
find_missing_elements(region_country['country'].unique().tolist(), population_final['country'].unique().tolist())
# Cette fonction va retourner une liste des pays qui sont présents dans region_country mais absents de population_final.
# La différence entre les deux appels à la fonction find_missing_elements réside dans la source et la cible des listes comparées, 
# ce qui influe sur les éléments identifiés comme manquants. 
# Le premier appel identifie les pays ayant des données de population qui ne sont pas reconnus dans l'index de pays (0 ici)
# (via region_country), tandis que le deuxième appel trouve les pays qui sont reconnus dans l'index mais pour lesquels 
# on n'a pas de données de population dans population_final.

['Andorra',
 'Niue',
 'Cook Islands',
 'San Marino',
 'Monaco',
 'Saint Kitts and Nevis',
 'Nauru',
 'Dominica',
 'Palau',
 'Republic of North Macedonia',
 'Tuvalu',
 'Marshall Islands']

In [44]:
# Changement du type des colonnes : 
population_final['country'] = population_final['country'].astype('string')
population_final['year'] = population_final['year'].astype('int')
population_final['female'] = population_final['female'].astype('int')
population_final['male'] = population_final['male'].astype('int')
population_final['rural'] = population_final['rural'].astype('int')
population_final['urban'] = population_final['urban'].astype('int')

In [45]:
# exportation du df en csv 
population_final.to_csv('population_final.csv', index=False)

### 4. Création de la  table water_access

In [47]:
# Importation du fichier BasicAndSafelyManagedDrinkingWaterServices : 
water_access = pd.read_csv('C:/Users/jorda/OneDrive/Documents/Projet_8/dossier_final_septembre/donnees_brut_DAN-P8-donnees/BasicAndSafelyManagedDrinkingWaterServices.csv')
water_access.describe()

,Year,Population using at least basic drinking-water services (%),Population using safely managed drinking-water services (%)
count,10476.000000,9415.000000,3286.000000
mean,2008.500000,83.962120,66.070856
std,5.188375,19.968269,30.383942
min,2000.000000,4.082620,0.000000
25%,2004.000000,75.928395,41.895583
50%,2008.500000,93.115400,73.966655
75%,2013.000000,98.954240,94.776640
max,2017.000000,100.000010,100.000000

In [48]:
# Vérification des valeurs nulles de water_access :
water_access.isnull().values.any()
print("Contient des valeurs nulles:", water_access.isnull().values.any())
wa_total_nulls = water_access.isnull().sum().sum()
wa_total_nulls
# Résultat : 8251 valeurs nulles

Contient des valeurs nulles: True

8251

In [49]:
# Transfomration de la table en pivot pour avoir une colonne pour chaque modalités de la colonne 'granularity' :
water_access_pivot = water_access.pivot(index=['Country','Year'], columns='Granularity', values='Population using at least basic drinking-water services (%)').reset_index()
water_access_pivot.head()

Granularity      Country  Year     Rural     Total     Urban
0            Afghanistan  2000  21.61913  27.77190  49.48745
1            Afghanistan  2001  21.61913  27.79726  49.48745
2            Afghanistan  2002  23.59988  29.90076  51.90447
3            Afghanistan  2003  25.58063  32.00507  54.32149
4            Afghanistan  2004  27.56138  34.12623  56.73851

In [50]:
# Filtrage des données
water_access_pivot_2 = water_access.loc[water_access['Granularity'] == 'Total'][['Year', 'Country', 'Population using safely managed drinking-water services (%)']]
water_access_pivot_2.head()

,Year,Country,Population using safely managed drinking-water services (%)
1,2000,Afghanistan,NaN
4,2000,Albania,49.29324
7,2000,Algeria,NaN
10,2000,Andorra,90.64000
13,2000,Angola,NaN

In [51]:
# Vérification des valeurs nulles de water_access_pivot_2 :
missing_v_water_access_pivot_2 = water_access_pivot_2.isna().sum().sum()
missing_v_water_access_pivot_2
print("Contient des valeurs nulles:", missing_v_water_access_pivot_2)
# Résultat : 1747 valeurs nulles

Contient des valeurs nulles: 1747

In [52]:
# Fusion des données
wa_pivot_final = pd.merge(water_access_pivot, water_access_pivot_2, on=['Year','Country'])
wa_pivot_final.head()

,Country,Year,Rural,Total,Urban,Population using safely managed drinking-water services (%)
0,Afghanistan,2000,21.61913,27.77190,49.48745,NaN
1,Afghanistan,2001,21.61913,27.79726,49.48745,NaN
2,Afghanistan,2002,23.59988,29.90076,51.90447,NaN
3,Afghanistan,2003,25.58063,32.00507,54.32149,NaN
4,Afghanistan,2004,27.56138,34.12623,56.73851,NaN

In [53]:
water_access

,Year,Country,Granularity,Population using at least basic drinking-water services (%),Population using safely managed drinking-water services (%)
0,2000,Afghanistan,Rural,21.61913,NaN
1,2000,Afghanistan,Total,27.77190,NaN
2,2000,Afghanistan,Urban,49.48745,NaN
3,2000,Albania,Rural,81.78472,NaN
4,2000,Albania,Total,87.86662,49.29324
...,...,...,...,...,...
10471,2017,Zambia,Total,59.96376,NaN
10472,2017,Zambia,Urban,83.86312,46.24515
10473,2017,Zimbabwe,Rural,49.80476,NaN
10474,2017,Zimbabwe,Total,64.05123,NaN
10475,2017,Zimbabwe,Urban,93.99767,NaN

In [54]:
# Changement du nom des colonnes :    
wa_pivot_final.rename(columns={'Country': 'country', 'Year':'year', 'Rural': 'rural_basic_water%', 'Total':'total_basic_water%', 'Urban': 'urban_basic_water%',
                             "Population using safely managed drinking-water services (%)":'total_safe_water%'}, inplace=True)
wa_pivot_final.head()

,country,year,rural_basic_water%,total_basic_water%,urban_basic_water%,total_safe_water%
0,Afghanistan,2000,21.61913,27.77190,49.48745,NaN
1,Afghanistan,2001,21.61913,27.79726,49.48745,NaN
2,Afghanistan,2002,23.59988,29.90076,51.90447,NaN
3,Afghanistan,2003,25.58063,32.00507,54.32149,NaN
4,Afghanistan,2004,27.56138,34.12623,56.73851,NaN

In [55]:
# Liste actuelle des colonnes
columns = ['country', 'year', 'rural_basic_water%', 'total_basic_water%', 'urban_basic_water%', 'total_safe_water%']

# Nouvel ordre des colonnes : échange de 'total_basic_water%' et 'urban_basic_water%'
new_order = ['country', 'year', 'rural_basic_water%', 'urban_basic_water%', 'total_basic_water%', 'total_safe_water%']

# Réindexation du DataFrame selon le nouvel ordre
wa_pivot_final = wa_pivot_final[new_order]

# Affichage des premières lignes du DataFrame modifié
wa_pivot_final.head()

,country,year,rural_basic_water%,urban_basic_water%,total_basic_water%,total_safe_water%
0,Afghanistan,2000,21.61913,49.48745,27.77190,NaN
1,Afghanistan,2001,21.61913,49.48745,27.79726,NaN
2,Afghanistan,2002,23.59988,51.90447,29.90076,NaN
3,Afghanistan,2003,25.58063,54.32149,32.00507,NaN
4,Afghanistan,2004,27.56138,56.73851,34.12623,NaN

In [56]:
# Fusion des données
wa_pivot_final_2 = pd.merge(wa_pivot_final, population_final, on=['country','year'])
wa_pivot_final_2.head()

,country,year,rural_basic_water%,urban_basic_water%,total_basic_water%,total_safe_water%,total,female,male,rural,urban
0,Afghanistan,2000,21.61913,49.48745,27.77190,NaN,20779953.0,10090449,10689508,15657474,4436282
1,Afghanistan,2001,21.61913,49.48745,27.79726,NaN,21606988.0,10489238,11117754,16318324,4648139
2,Afghanistan,2002,23.59988,51.90447,29.90076,NaN,22600770.0,10958668,11642106,17086910,4893013
3,Afghanistan,2003,25.58063,54.32149,32.00507,NaN,23680871.0,11466237,12214634,17909063,5155788
4,Afghanistan,2004,27.56138,56.73851,34.12623,NaN,24726684.0,11962963,12763726,18692107,5426872

In [57]:
# Ajout de la population totale
wa_pivot_final_2['population_totale'] = wa_pivot_final_2['female'] + wa_pivot_final_2['male']
wa_pivot_final_2.head()

,country,year,rural_basic_water%,urban_basic_water%,total_basic_water%,total_safe_water%,total,female,male,rural,urban,population_totale
0,Afghanistan,2000,21.61913,49.48745,27.77190,NaN,20779953.0,10090449,10689508,15657474,4436282,20779957
1,Afghanistan,2001,21.61913,49.48745,27.79726,NaN,21606988.0,10489238,11117754,16318324,4648139,21606992
2,Afghanistan,2002,23.59988,51.90447,29.90076,NaN,22600770.0,10958668,11642106,17086910,4893013,22600774
3,Afghanistan,2003,25.58063,54.32149,32.00507,NaN,23680871.0,11466237,12214634,17909063,5155788,23680871
4,Afghanistan,2004,27.56138,56.73851,34.12623,NaN,24726684.0,11962963,12763726,18692107,5426872,24726689

In [58]:
# Ajout de colonnes / calculs dérivés qui appliquent les pourcentages de couverture de l'eau à la population respective 
# pour estimer combien de personnes sont effectivement desservies en millions
wa_pivot_final_2['rural_basic_water_m'] = round((wa_pivot_final_2['rural_basic_water%'] / 100) * wa_pivot_final_2['rural'], 0)
wa_pivot_final_2['urban_basic_water_m'] = round((wa_pivot_final_2['urban_basic_water%'] / 100) * wa_pivot_final_2['urban'], 0)
wa_pivot_final_2['total_basic_water_m'] = round((wa_pivot_final_2['total_basic_water%'] / 100) * wa_pivot_final_2['population_totale'], 0)
wa_pivot_final_2['total_safe_water_m'] = round((wa_pivot_final_2['total_safe_water%'] / 100) * wa_pivot_final_2['population_totale'], 0)
wa_pivot_final_2.head()

,country,year,rural_basic_water%,urban_basic_water%,total_basic_water%,total_safe_water%,total,female,male,rural,urban,population_totale,rural_basic_water_m,urban_basic_water_m,total_basic_water_m,total_safe_water_m
0,Afghanistan,2000,21.61913,49.48745,27.77190,NaN,20779953.0,10090449,10689508,15657474,4436282,20779957,3385010.0,2195403.0,5770989.0,NaN
1,Afghanistan,2001,21.61913,49.48745,27.79726,NaN,21606988.0,10489238,11117754,16318324,4648139,21606992,3527880.0,2300245.0,6006152.0,NaN
2,Afghanistan,2002,23.59988,51.90447,29.90076,NaN,22600770.0,10958668,11642106,17086910,4893013,22600774,4032490.0,2539692.0,6757803.0,NaN
3,Afghanistan,2003,25.58063,54.32149,32.00507,NaN,23680871.0,11466237,12214634,17909063,5155788,23680871,4581251.0,2800701.0,7579079.0,NaN
4,Afghanistan,2004,27.56138,56.73851,34.12623,NaN,24726684.0,11962963,12763726,18692107,5426872,24726689,5151803.0,3079126.0,8438287.0,NaN

In [59]:
# Réorganisation des colonnes (trie)
eau_potable_final = wa_pivot_final_2[['country','year','population_totale', 'rural_basic_water_m','urban_basic_water_m','total_basic_water_m','total_safe_water_m']].copy() 
eau_potable_final.head()

,country,year,population_totale,rural_basic_water_m,urban_basic_water_m,total_basic_water_m,total_safe_water_m
0,Afghanistan,2000,20779957,3385010.0,2195403.0,5770989.0,NaN
1,Afghanistan,2001,21606992,3527880.0,2300245.0,6006152.0,NaN
2,Afghanistan,2002,22600774,4032490.0,2539692.0,6757803.0,NaN
3,Afghanistan,2003,23680871,4581251.0,2800701.0,7579079.0,NaN
4,Afghanistan,2004,24726689,5151803.0,3079126.0,8438287.0,NaN

In [60]:
# Convertion de la colonne 'country' en type 'string' pour une manipulation uniforme du texte.
eau_potable_final['country'] = eau_potable_final['country'].astype('string')

In [61]:
# exportation du df eau_potable_final en csv 
eau_potable_final.to_csv('eau_potable_final.csv', index=False)

### 5. Création de la  table water_mortality

In [63]:
# Importation du fichier MortalityRateAttributedToWater : 
water_mortality = pd.read_csv('C:/Users/jorda/OneDrive/Documents/Projet_8/dossier_final_septembre/donnees_brut_DAN-P8-donnees/MortalityRateAttributedToWater.csv')
water_mortality.describe()

,Year,Mortality rate attributed to exposure to unsafe WASH services,WASH deaths
count,549.0,549.000000,183.000000
mean,2016.0,12.493876,4756.097706
std,0.0,20.830508,21280.125369
min,2016.0,0.003960,0.082290
25%,2016.0,0.192960,11.163275
50%,2016.0,1.288710,130.983400
75%,2016.0,18.054780,1950.433500
max,2016.0,107.048020,246087.900000

In [64]:
# Vérification des valeurs nulles de water_mortality :
water_mortality.isnull().values.any()
print("Contient des valeurs nulles:", water_mortality.isnull().values.any())
wm_total_nulls = water_mortality.isnull().sum().sum()
wm_total_nulls
# Résultat : 366 valeurs nulles

Contient des valeurs nulles: True

366

In [65]:
# Transfomration de la table en pivot pour avoir une colonne pour chaque modalités de la colonne 'granularity' :
wm_pivot_1 = water_mortality.pivot(index=['Country','Year'], columns='Granularity', values='Mortality rate attributed to exposure to unsafe WASH services').reset_index()
wm_pivot_1.head()

Granularity              Country  Year    Female      Male     Total
0                    Afghanistan  2016  15.31193  12.61297  13.92067
1                        Albania  2016   0.12552   0.20650   0.16641
2                        Algeria  2016   2.19890   1.72837   1.86723
3                         Angola  2016  45.15024  52.62506  48.81467
4            Antigua and Barbuda  2016   0.10419   0.12469   0.11403

In [66]:
# Filtrage des donnnées
wm_pivot_2 = water_mortality.loc[water_mortality['Granularity'] == 'Total'][['Year', 'Country', 'WASH deaths']]
wm_pivot_2.head()

    Year              Country  WASH deaths
2   2016          Afghanistan   4824.35300
5   2016              Albania      4.86975
8   2016              Algeria    758.21000
11  2016               Angola  14065.20000
14  2016  Antigua and Barbuda      0.11513

In [67]:
# Fusion des données
wm_pivot_final = pd.merge(wm_pivot_1, wm_pivot_2, on=['Country','Year'])
wm_pivot_final.rename(columns={'Country':'country','Year':'year','Female': 'female_(100k)', 'Male':'male_(100k)', 'Total':'total_(100k)'}, inplace=True)
wm_pivot_final.head()

,country,year,female_(100k),male_(100k),total_(100k),WASH deaths
0,Afghanistan,2016,15.31193,12.61297,13.92067,4824.35300
1,Albania,2016,0.12552,0.20650,0.16641,4.86975
2,Algeria,2016,2.19890,1.72837,1.86723,758.21000
3,Angola,2016,45.15024,52.62506,48.81467,14065.20000
4,Antigua and Barbuda,2016,0.10419,0.12469,0.11403,0.11513

In [68]:
# Filtrage des données et changement du nom des colonnes / Etant donné que les données soient essentiellement accées sur l'année 2016 dans
# la table water_mortality nous choisisrons l'année 2016 comme filtre
population_2016 = population_final.loc[population_final['year'] == 2016].copy()
population_2016.rename(columns={'p_country_name': 'country', 'p_year':'year'}, inplace=True)
population_2016.head()

granularity,country,year,total,female,male,rural,urban
16,Afghanistan,2016,35383032.0,17196034,18186994,25985093,8670939
35,Albania,2016,2886438.0,1415879,1470548,1216737,1709611
54,Algeria,2016,40551392.0,20069497,20481901,11589537,29016515
111,Angola,2016,28842489.0,14576127,14266355,10329860,18483603
149,Antigua and Barbuda,2016,94527.0,49002,45518,75878,25085

In [69]:
# Fusion des données
wm_pivot_final_2 = pd.merge(wm_pivot_final, population_2016, on=['country','year'])
wm_pivot_final_2.head()

,country,year,female_(100k),male_(100k),total_(100k),WASH deaths,total,female,male,rural,urban
0,Afghanistan,2016,15.31193,12.61297,13.92067,4824.35300,35383032.0,17196034,18186994,25985093,8670939
1,Albania,2016,0.12552,0.20650,0.16641,4.86975,2886438.0,1415879,1470548,1216737,1709611
2,Algeria,2016,2.19890,1.72837,1.86723,758.21000,40551392.0,20069497,20481901,11589537,29016515
3,Angola,2016,45.15024,52.62506,48.81467,14065.20000,28842489.0,14576127,14266355,10329860,18483603
4,Antigua and Barbuda,2016,0.10419,0.12469,0.11403,0.11513,94527.0,49002,45518,75878,25085

In [70]:
# Ajout de colonnes / calculs dérivés qui appliquent les pourcentages de couverture de l'eau à la population respective 
# pour estimer combien de personnes sont effectivement desservies en millions
wm_pivot_final_2['female_wd'] = wm_pivot_final_2['female_(100k)'] * wm_pivot_final_2['female'] / 100000
wm_pivot_final_2['male_wd'] = wm_pivot_final_2['male_(100k)'] * wm_pivot_final_2['male'] / 100000
wm_pivot_final_2['total_deaths'] = wm_pivot_final_2['female_wd'] + wm_pivot_final_2['male_wd']
wm_pivot_final_2.head()

,country,year,female_(100k),male_(100k),total_(100k),WASH deaths,total,female,male,rural,urban,female_wd,male_wd,total_deaths
0,Afghanistan,2016,15.31193,12.61297,13.92067,4824.35300,35383032.0,17196034,18186994,25985093,8670939,2633.044689,2293.920097,4926.964786
1,Albania,2016,0.12552,0.20650,0.16641,4.86975,2886438.0,1415879,1470548,1216737,1709611,1.777211,3.036682,4.813893
2,Algeria,2016,2.19890,1.72837,1.86723,758.21000,40551392.0,20069497,20481901,11589537,29016515,441.308170,354.003032,795.311202
3,Angola,2016,45.15024,52.62506,48.81467,14065.20000,28842489.0,14576127,14266355,10329860,18483603,6581.156323,7507.677879,14088.834202
4,Antigua and Barbuda,2016,0.10419,0.12469,0.11403,0.11513,94527.0,49002,45518,75878,25085,0.051055,0.056756,0.107812

In [71]:
# Filtrage des données et changement du nom des colonnes 
water_mortality_2016_final = wm_pivot_final_2[['country','year', 'WASH deaths', 'female_wd','male_wd']].copy()
water_mortality_2016_final.rename(columns={'WASH deaths':'total_deaths', 'female_wd':'female_deaths','male_wd':'male_deaths'}, inplace=True)
water_mortality_2016_final.head()

               country  year  total_deaths  female_deaths  male_deaths
0          Afghanistan  2016    4824.35300    2633.044689  2293.920097
1              Albania  2016       4.86975       1.777211     3.036682
2              Algeria  2016     758.21000     441.308170   354.003032
3               Angola  2016   14065.20000    6581.156323  7507.677879
4  Antigua and Barbuda  2016       0.11513       0.051055     0.056756

In [72]:
# Exporation du df en csv 
water_mortality_2016_final.to_csv('water_mortality_2016_final.csv', index=False)

## 6. Fusion des tables et chargement dans la BDD postgreSQL

### 6.1 Création de la table fao_data

In [75]:
# Fusion des données et changement du nom des colonnes
fao_data = pd.merge(wa_pivot_final_2, political_stability_final, how='left', left_on=['country','year'], right_on=['country','year'])[['country','year','female', 'male', 'rural', 'urban','political_stability','rural_basic_water_m', 'urban_basic_water_m', 'total_basic_water_m','total_safe_water_m']]

# Remmplacement des valeurs manquantes par 0
fao_data.fillna(0, inplace = True)
fao_data.head()

# male, female, rural , urban, rural_basic_water_m, urban_basic_water_m, total_basic_water_m, total_safe_water_m  = population

,country,year,female,male,rural,urban,political_stability,rural_basic_water_m,urban_basic_water_m,total_basic_water_m,total_safe_water_m
0,Afghanistan,2000,10090449,10689508,15657474,4436282,-2.44,3385010.0,2195403.0,5770989.0,0.0
1,Afghanistan,2001,10489238,11117754,16318324,4648139,0.00,3527880.0,2300245.0,6006152.0,0.0
2,Afghanistan,2002,10958668,11642106,17086910,4893013,-2.04,4032490.0,2539692.0,6757803.0,0.0
3,Afghanistan,2003,11466237,12214634,17909063,5155788,-2.20,4581251.0,2800701.0,7579079.0,0.0
4,Afghanistan,2004,11962963,12763726,18692107,5426872,-2.30,5151803.0,3079126.0,8438287.0,0.0

In [76]:
# Exportation du df en csv
fao_data.to_csv('fao_data.csv', index=False)

In [77]:
# Création de l'engine
engine = create_engine('postgresql+psycopg2://postgres:12345@localhost:5433/projet_8_oc')

try:
    # Création d'une session
    with Session(engine) as session:
        # Exécution d'une requête simple
        result = session.execute(text("SELECT 'Success!' AS message"))
        # Affichage des résultats, assurez-vous que 'message' est utilisé correctement
        for row in result.mappings():  # Utilisez mappings() pour retourner des objets Row
            print(row['message'])  # Accès par nom de colonne
except Exception as e:
    print("Une erreur est survenue lors de la connexion à la base de données:")
    print(e)

# Explication : session.execute(): Exécute la requête.
# result.mappings(): Retourne un itérable qui produit des objets Row. Chaque Row peut être accédé par des indices numériques ou des noms de colonnes.

Success!

In [78]:
# Configuration de la connexion à la base de données
engine = create_engine('postgresql+psycopg2://postgres:12345@localhost:5433/projet_8_oc')

# Chargement du fichier CSV dans un DataFrame
file_path = 'C:/Users/jorda/OneDrive/Documents/Projet_8/dossier_final_septembre/donnees_nettoyees_via_notebook/fao_data.csv'
df = pd.read_csv(file_path)

# Nettoyage des données au besoin
# Par exemple, vous pourriez vouloir remplacer les valeurs NaN par des zéros ou effectuer d'autres transformations:
df.fillna(0, inplace=True)

# Chargement des données du DataFrame dans la table SQL
# S'assurer que le nom de la table 'fao_data' existe dans la base de données et que les schémas des colonnes correspondent
df.to_sql('fao_data', con=engine, if_exists='append', index=False)

print("Les données ont été chargées avec succès dans la base de données PostgreSQL.")

Les données ont été chargées avec succès dans la base de données PostgreSQL.

### 6.2 Création de la table water_mortality_2016_final_2

In [80]:
water_mortality_2016_final_2 = water_mortality_2016_final[['country', 'female_deaths', 'male_deaths']]
water_mortality_2016_final_2.head()

               country  female_deaths  male_deaths
0          Afghanistan    2633.044689  2293.920097
1              Albania       1.777211     3.036682
2              Algeria     441.308170   354.003032
3               Angola    6581.156323  7507.677879
4  Antigua and Barbuda       0.051055     0.056756

In [81]:
water_mortality_2016_final_2

                                country  female_deaths  male_deaths
0                           Afghanistan    2633.044689  2293.920097
1                               Albania       1.777211     3.036682
2                               Algeria     441.308170   354.003032
3                                Angola    6581.156323  7507.677879
4                   Antigua and Barbuda       0.051055     0.056756
..                                  ...            ...          ...
177  Venezuela (Bolivarian Republic of)     205.947133   209.056091
178                            Viet Nam     534.257436   987.047119
179                               Yemen    1586.064606  1187.027240
180                              Zambia    2746.531196  2965.696551
181                            Zimbabwe    1630.404269  1806.499329

[182 rows x 3 columns]

In [82]:
# Exporation du df en csv 
water_mortality_2016_final_2.to_csv('water_mortality_2016_final_2.csv', index=False)

In [83]:
# Chargement du fichier CSV dans un DataFrame

# Configuration de la connexion à la base de données
engine = create_engine('postgresql+psycopg2://postgres:12345@localhost:5433/projet_8_oc')

# Chargement du fichier CSV dans un DataFrame
file_path2 = 'C:/Users/jorda/OneDrive/Documents/Projet_8/dossier_final_septembre/donnees_nettoyees_via_notebook/water_mortality_2016_final_2.csv'
df2 = pd.read_csv(file_path2)

# Nettoyage des données au besoin
# Par exemple, vous pourriez vouloir remplacer les valeurs NaN par des zéros ou effectuer d'autres transformations:
df2.fillna(0, inplace=True)

# Chargement des données du DataFrame dans la table SQL
# S'assurer que le nom de la table 'fao_data' existe dans la base de données et que les schémas des colonnes correspondent
df2.to_sql('water_mortality_2016_final_2', con=engine, if_exists='append', index=False)

print("Les données ont été chargées avec succès dans la base de données PostgreSQL.")

Les données ont été chargées avec succès dans la base de données PostgreSQL.

In [84]:
# Implémentation de country_region dans la bdd
region_country.to_sql('country_region', con=engine, if_exists='append', index=False)

194

In [85]:
--

SyntaxError: invalid syntax (3659366440.py, line 1)

In [ ]:
region_country.to_sql('country_region', con=engine, if_exists='append', index=False)

In [ ]:
# Insérez les DataFrames dans la base de données
region_country.to_sql('country_region', con=engine, if_exists='append', index=False)
fao_data.to_sql('fao_data', con=engine, if_exists='append', index=False)
water_mortality_2016_final_2.to_sql('water_mortality_2016_final', con=engine, if_exists='append', index=False)

In [ ]:
water_mortality_2016_final_2.columns